guest=['xr','lmd','lz']
print(guest)
print(guest[2].title()+" can not join the party!")
guest.remove('lz')
guest.insert(2,'hzz')
print("Today I invite "+guest[0].title()+" "+guest[1].title()+" "+guest[2].title()+" "+"join the party")
print("Now I find a big table, so I can invite more people and three person will join the party!")
guest.insert(0,'lhm')
guest.insert(2,'wjx')
guest.append('qzx')
print(guest)
print("What a pity! The table can not send my house,so I can only invite two person to join the party now !")
guest_one=guest.pop()
print("I am so sorry that I can not invite "+guest_one+" to join the party!")
guest_two=guest.pop()
print("I am so sorry that I can not invite "+guest_two+" to join the party!")
guest_three=guest.pop()
print("I am so sorry that I can not invite "+guest_three+" to join the party!")
guest_four=guest.pop()
print("I am so sorry that I can not invite "+guest_four+" to join the party!")
print(guest)
print("Today I invite "+guest[0].title()+" "+guest[1].title()+" "+"join the party")
print(len(guest))
del guest[0]
del guest[0]
print(guest)
